2024-01-02 00:10:51,319 - ERROR - An error occurred in admin_users route: Encountered unknown tag 'extend'.
Traceback (most recent call last):
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 152, in blog
    return render_template("blog.html")
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\blog.html", line 1, in template
    {% extend layou %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'extend'.
2024-01-02 00:11:26,530 - ERROR - An error occurred in admin_users route: Encountered unknown tag 'extend'.
Traceback (most recent call last):
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 152, in blog
    return render_template("blog.html")
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\blog.html", line 1, in template
    {% extend layout %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'extend'.
2024-01-02 00:11:34,103 - ERROR - An error occurred in admin_users route: Encountered unknown tag 'extend'.
Traceback (most recent call last):
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 152, in blog
    return render_template("blog.html")
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\blog.html", line 1, in template
    {% extend layout %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'extend'.
2024-01-02 00:12:03,159 - ERROR - An error occurred in admin_users route: 'layout' is undefined
Traceback (most recent call last):
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 152, in blog
    return render_template("blog.html")
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\blog.html", line 1, in top-level template code
    {% extends layout %}
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 96, in _get_source_fast
    return loader.get_source(environment, template)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 195, in get_source
    pieces = split_template_path(template)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 30, in split_template_path
    for piece in template.split("/"):
jinja2.exceptions.UndefinedError: 'layout' is undefined
2024-01-02 00:13:34,455 - ERROR - An error occurred in admin_users route: 'layout' is undefined
Traceback (most recent call last):
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 150, in blog
    return render_template("blog.html")
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\DELL\OneDrive\Desktop\FURTHER UPGRADE\cs50_final_project\app\templates\blog.html", line 1, in top-level template code
    {% extends layout %}
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 96, in _get_source_fast
    return loader.get_source(environment, template)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 195, in get_source
    pieces = split_template_path(template)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 30, in split_template_path
    for piece in template.split("/"):
jinja2.exceptions.UndefinedError: 'layout' is undefined
